### ISSUE TITLE
Willy won't add me :'(

### ISSUE THREAD

**Issue by Tom-Hayes** [willyzha/PeekBot#2]
Willy won't add me :'(
![Sad Noot](https://user-images.githubusercontent.com/50387112/67530909-a9702a00-f68e-11e9-9801-b7f6fe743ee4.png)

**Comment by WasimSaad** [comment]
>6 years programming experience only. Keep applying Im sure you'll get in somewhere

**Comment by willyzha** [comment]
Added @tomtwin to the lost of contributors
